---
title: "Python para Dados: Minha Jornada na Análise!"
author: "Sergio Pedro Rodrigues Oliveira"
date: "`r Sys.Date()`"
output: github_document
---

\thispagestyle{empty}

\newpage
\pagenumbering{roman}

```{=latex}
\setcounter{tocdepth}{4}
\renewcommand{\contentsname}{SUMÁRIO}
\tableofcontents
```

\newpage

```{=latex}
\setcounter{tocdepth}{4}
\renewcommand{\listfigurename}{LISTA DE FIGURAS}
\listoffigures
```

\newpage

```{=latex}
\setcounter{tocdepth}{4}
\renewcommand{\listtablename}{LISTA DE TABELAS}
\listoftables
```

```{r Pacotes, message=FALSE, warning=FALSE, echo=FALSE}
library(knitr)
library(rmarkdown)
library(readr)
library(tibble)
library(magrittr)
library(dplyr)
library(tidyr)
library(data.table)
library(janitor)
```

\newpage

Bem-vindo(a) ao **Python para Dados**, meu espaço para estudar e me aprofundar em **Python** focado em **ciência e análise de dados**. Aqui, concentro meus estudos, códigos e recursos das principais bibliotecas como **Pandas** e **NumPy**. Meu objetivo é documentar e compartilhar minha jornada de aprendizado contínuo nesse universo.

---

## 🎯 Objetivo do Repositório

Este repositório serve como um diário de bordo dos meus estudos. Você encontrará:

* **Códigos de exemplos:** Trechos de código e scripts para praticar conceitos.
* **Projetos e exercícios:** Aplicações práticas para fixar o aprendizado.
* **Anotações e resumos:** Pontos chave sobre bibliotecas e teorias.

---

## 🛠️ Tecnologias Utilizadas

* **Python:** A linguagem principal para análise de dados.
* **Pandas:** Manipulação e análise de dados tabulares.
* **NumPy:** Computação numérica eficiente com arrays.
* **Matplotlib / Seaborn:** Para visualização de dados.
* Outras bibliotecas que surgirem ao longo do caminho!

---

## 🚀 Como Explorar

Sinta-se à vontade para navegar pelos diretórios. Cada pasta ou arquivo estará organizado de forma a facilitar a compreensão dos tópicos abordados.